name: automerge
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto approve
        if:  startsWith(github.head_ref, 'entries-')
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.PAT }}
      - name: Auto merge
        run: gh pr merge --squash --auto ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
