name: filecheck
on: pull_request

jobs:
  filecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            readme.md

      - name: Check changed files
        if: steps.changed-files.outputs.any_changed == 'true' && github.actor != 'bntzio'
        run: |
          echo "Attempting to change a generated file. This is not allowed."
          exit 1
