name: filecheck
on: pull_request

jobs:
  filecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@3032ed12385efa3ba02db737b66f90dcd2d28f64
        with:
          files: |
            readme.md

      - name: Unathorized file change
        if: steps.changed-files.outputs.any_changed == 'true' && github.actor != 'bntzio'
        run: |
          echo "Attempting to change a generated file. This is not allowed."
          exit 1
